# Generated by Django 4.2.7 on 2023-11-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_contactus_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
