# Generated by Django 4.2.7 on 2023-11-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
