# Generated by Django 4.2.7 on 2023-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prossyApp', '0007_product_gender_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'women'), ('men', 'men')], default='Women', max_length=100),
        ),
    ]
