# Generated by Django 4.2.7 on 2023-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prossyApp', '0008_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'women'), ('men', 'men'), ('all', 'all')], default='Women', max_length=100),
        ),
    ]
