# Generated by Django 4.2.7 on 2023-11-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prossyApp', '0010_alter_cartorderitems_options_address_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='1500.00', max_digits=10, null=True),
        ),
    ]
